dist: bionic
language: ruby
cache: bundler
rvm:
  - 2.6.5
services:
  - postgresql

before_install:
  - gem install bundler

jobs:
  include:
    - name: rubocop & rails test
      script:
        - bundle exec rubocop
        - bundle exec rails test:db
