default: &default
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  namespace: scalelite_development

test:
  <<: *default
  namespace: scalelite_test

production:
  <<: *default
  url: <%= ENV['REDIS_URL'] %>
  namespace: <%= ENV.fetch('REDIS_NAMESPACE') { 'scalelite' } %>
